# THERE IS AN ORDER THAT MUST BE FOLLOWED WHEN
# INSERTING DATA INTO TABLES IN A DATABASE. THE ORDER IS
# BASED ON THE NUMBER OF FOREIGN KEYS IN A TABLE.
# START WITH THE TABLES THAT HAVE NO FOREIGN KEYS.
# THEN CREATE THE TABLES THAT HAVE ONLY ONE FOREIGN KEY.
# THEN CREATE TABLES THAT TWO FOREIGN KEYS ETC.

# INSERT DATA INTO ONLY SPECIFIED COLUMNS
INSERT INTO CUSTOMER(CUS_CODE, CUS_LNAME, CUS_FNAME, CUS_INITIAL, CUS_PHONE)
VALUES (10010, 'RAMAS', 'ALFRED', 'A', '844-2573');

# INSERT DATA INTO ALL COLUMNS OF THE CUSTOMER TABLE
INSERT INTO CUSTOMER
VALUES (10011, 'DUNNE', 'LEONA', 'K', '713', '844-3245', 0.00);

# INSERT DATA INTO ONLY SPECIFIED COLUMNS OF THE VENDOR TABLE
INSERT INTO VENDER (V_CODE, V_NAME, V_CONTACT, V_AREACODE, V_PHONE, V_STATE)
VALUE (21231, 'D&E SUPPLY', 'SINGH', '615', '228-1238', 'TN');

# INSERT DATA INTO ALL COLUMNS OF THE VENDOR TABLE
INSERT INTO VENDER
VALUES (21226, 'SUPERLOO INC', 'FLUSHING', '904', '215-8995', 'TN', 'N');

# INSERT DATA INTO ALL COLUMNS OF THE PRODUCT TABLE
INSERT INTO PRODUCT
VALUES ('11QER/31', 'POWER PAINTER', '2011-11-03', 8, 5, 109.99, 0.00, 21226, 25, 0);

# INSERT DATA INTO ALL COLUMNS OF THE INVOICE TABLE
INSERT INTO INVOICE
VALUES (1001, 10011, '2012-01-15', 24.90, 1.99, 26.89);

# INSERT DATA INTO ALL COLUMNS OF THE LINE TABLE
INSERT INTO LINE
VALUES (1001, 1, '11QER/31', 1, 14.99, 14.99);