# CREATED THE SALESCO DATABASE
CREATE SCHEM IF NOT EXISTS SALESCO;

# DROPPED THE SALESCO DATABASE
# DROP SCHEMA SALESCO;

# USE SALESCO;

# THERE IS AN ORDER THAT MUST BE FOLLOWED WHEN
# CREATING TABLES IN A DATABASE. THE ORDER IS
# BASED ON THE NUMBER OF FOREIGN KEYS IN A TABLE.
# START WITH THE TABLES THAT HAVE NO FOREIGN KEYS.
# THEN CREATE THE TABLES THAT HAVE ONLY ONE FOREIGN KEY.
# THEN CREATE TABLES THAT TWO FOREIGN KEYS ETC.

# CREATED THE CUSTOMER TABLE
CREATE TABLE IF NOT EXISTS CUSTOMER {
	CUS_CODE INT NOT NULL,
    CUS_LNAME VARCHAR(15) NOT NULL,
    CUS_FNAME VARCHAR(15) NOT NULL,
    CUS_INITIAL CHAR(1) NULL,
    CUS_AREACODE CHAR(3) NOT NULL DEFAUL '615',
    CUS_PHONE CHAR(8) NOT NULL,
    CUS_BALANCE DECIMAL(9,2) NULL DEFAUL 0.00,
    PRIMARY KEY (CUS_CODE)
);

# CREATED THE VENDOR TABLE
CREATE TABLE IF NOT EXISTS VENDOR (
	V_CODE INT NOT NULL,
    V_NAME VARCHAR(35) NOT NULL,
    V_CONTACT VARCHAR(35) NOT NULL,
    V_AREACODE CHAR(3) NOT NULL,
    V_PHONE CHAR(8) NOT NULL,
    V_STATE CHAR(2) NOT NULL,
    V_ORDER CHAR(1) NULL,
    PRIMARY KEY (V_CODE)
);

# CREATED THE PRODUCT TABLE
CREATE TABLE IF NOT EXISTS PRODUCT (
	P_CODE VARTCHAR(10) NOT NULL,
    P_DESCRIPT VARCHAR(35) NOT NULL,
    P_INDATE DATE NOT NULL,
    P_QOH SMALLINT NOT NULL,
    P_MIN SMALLINT NOT NULL,
    P_PRICE DECIMAL(8,2) NULL,
    P_DISCOUNT DECIMAL(5,2) NOT NULL,
    V_CODE INT NULL,
    P_SALESCODE CHAR(1) NULL,
    PRIMARY KEY (P_CODE),
    CONSTRAINT PRODUCT_VENDOR_FK
		FOREIGN KEY (V_CODE)
        REFERENCES VENDOR (V_CODE)
);

# CREATED THE INVOICE TABLE
CREATE TABLE IF NOT EXISTS INVOICE (
	INV_NUM INT NOT NULL,
    CUS_CODE INT NOT NULL,
    INV_DATE DATE NOT NULL,
    PRIMARY KEY (INV_NUM),
    CONTRAINT INVOICE_CUSTOMER_FK
		FOREIGN KEY (CUS_CODE)
        REFERENCES CUSTOMER (CUS_CODE)
);

# CREATED THE LINE TABLE
CREATE TABLE IF NOT EXISTS LINE (
	INV_NUM INT NOT NULL,
    LINE_NUMBER DECIMAL(2,0) NOT NULL,
    P_CODE VARCHAR(10) NOT NULL,
    LINE_UNITS DECIMAL(9,2) NOT NULL,
    LINE_PRICE DECIMAL(9,2) NOT NULL,
    PRIMARY KEY (INV_NUM, LINE_NUMBER),
    CONSTRAINT LINE_PRODUCT_FK
		FOREIGN KEY (P_CODE)
        REFERENCES PRODUCT (P_CODE,
	CONSTRAINT LINE_INVOICE_FK
		FOREIGN KEY (INV_NUM)
        REFERENCES INVOICE (INV_NUM)
);

# THERE IS AN ODERE FOR DROPPING TABLES
# START WITH THE TABLE THAT HAS THE MOST FOREIGN
# KEYS AND END WITH THE LEAST AMOUNT
DROP TABLE LINE;
DROP TABLE PRODUCT;
DROP TABLE INVOICE;
DROP TABLE VENDOR;
DROP TABLE CUSTOMER;

# CREATED AN INDEX IN THE CUSTOMER TABLE
CREATE INDEX CUSTOMER_LNAME_FNAME_IDX ON CUSTOMER (CUST_LNAME, CUS_FNAME);

# DELETED THE INDEX IN THE CUSTOMER TABLE
DROP INDEX CUSTOMER_LNAME_FNAME_IDX ON CUSTOMER;

# MODIFIED THE DATA TYPE OF THE P_PRICE COLUMN ON THE PRODUCT TABLE
ALTER TABLE PRODUCT
	MODIFY P_PRICE DECIMAL(9,2);
    
# DELTED THE P_SALESCODE COLUMN FROM THE PRODUCT TABLE
ALTER TABLE PRODUCT
	DROP P_SALESCODE;
    
# ADDED 3 NEW COLUMNS TO THE INVOICE TABLE
ALTER TABLE INVOICE
	ADD INV_SUBTOTAL DECIMAL(9,2),
    ADD INV_TAX DECIMAL(9,2),
    ADD INV_TOTAL DECIMAL(9,2);

# DIDNT MODIFY THE DATA TYPE OF THE V_CODE COLUMN IN VENDOR
ALTER TABLE VENDOR
	MODIFY V_CODE VARCHAR(6);
    
ALTER TABLE PRODUCT
	MODIFY V_CODE VARCHAR(6);
    
CREATE TABLE IF NOT EXISTS PART AS 
SELECT P_CODE AS PART_CODE,
	P_DESCRIPT AS PART_DESCRIPT,
    P_PRICE AS PART_PRICE,
    V_CODE
FROM PRODUCT;

# ADDED PRIMARY KEY TO PART
ALTER TABLE PART
	ADD PRIMARY KEY (PART_CODE);
    
ALTER TABLE PART
	ADD FOREIGN KEY (V_CODE) REFERENCES VENDOR (V_CODE);
    
ALTER TABLE PRODUCT
	ADD P_MIN_ORDER INT NOT NULL,
	ADD P_REORDER INT NOT NULL;
    
ALTER TABLE LINE
	ADD LINE_TOTAL DECIMAL(9,2) NOT NULL;